
CREATE TABLE  IF NOT EXISTS mpa (
	mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text
	);
	
CREATE TABLE  IF NOT EXISTS status (
	status_id INTEGER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL
	);

CREATE TABLE  IF NOT EXISTS genre (
	genre_id INTEGER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text
	);


CREATE TABLE  IF NOT EXISTS users (
    user_id INTEGER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
	email text,
	login text NOT NULL,
	name text,
	birthday date
   ); 


CREATE TABLE  IF NOT EXISTS films (
    film_id INTEGER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
	description varchar(200),
	name text NOT NULL,
	release_date date NOT NULL,
	duration INTEGER NOT NULL,
	mpa_id INTEGER REFERENCES mpa(mpa_id) 
	);
	


CREATE TABLE  IF NOT EXISTS likes (
 film_id INTEGER REFERENCES films(film_id),
 user_id INTEGER REFERENCES users(user_id)
);


CREATE TABLE  IF NOT EXISTS friends (
 user_id INTEGER REFERENCES users(user_id),
 friend_id INTEGER REFERENCES users(user_id),
 status INTEGER REFERENCES status(status_id)
);



CREATE TABLE  IF NOT EXISTS films_genre_mapping (
 genre_id INTEGER REFERENCES genre(genre_id),
 film_id INTEGER REFERENCES films(film_id)
);